version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "4318:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this password
    volumes:
      - grafana-data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    command: "-config.file=/etc/tempo/tempo.yml"
    container_name: tempo
    ports:
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml

  alloy:
    volumes:
      - /root/config.alloy:/etc/alloy/config.alloy
    ports:
      - 12345:12345
    image: grafana/alloy:latest
    command: run --stability.level=experimental --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
volumes:
  grafana-data:
